---
development:
  cloud_name: rashi
  api_key: '299957439382349'
  api_secret: T-p52ID4QRy_XxL71knJF9knQus
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: rashi
  api_key: '299957439382349'
  api_secret: T-p52ID4QRy_XxL71knJF9knQus
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: rashi
  api_key: '299957439382349'
  api_secret: T-p52ID4QRy_XxL71knJF9knQus
  enhance_image_tag: true
  static_image_support: false
